
GET http://localhost:8000/products/ HTTP/1.1

###

GET http://localhost:8000/products/2/ HTTP/1.1


###

PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MTQyNjM4LCJpYXQiOjE3NzQxNDIzMzgsImp0aSI6IjdkMDA0NWVkY2FmMTRkZTU5MDNmMmJiNGE2NDM0MmQ0IiwidXNlcl9pZCI6IjIifQ.VdIVE77EsxjbpbeXtVerlYwLZWr-7b8EY8kB7Gcx0ME

{
	"name": "Television",
	"price": 300.00,
	"stock": 14,
	"description": "An amazing new TV"
}


###

DELETE http://localhost:8000/products/1/ HTTP/1.1


###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MDk2Nzg0LCJpYXQiOjE3NzQwOTY0ODQsImp0aSI6IjhlYzY0OGYxNGM4ZTRlYzE4MjY5OThkYzM0ZDVlNThkIiwidXNlcl9pZCI6IjIifQ.hrWzM-JlbElWbk8gd2yQaUc_f5sybnAiJgbRXV-gCAI
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MDk2NjQ1LCJpYXQiOjE3NzQwOTYzNDUsImp0aSI6ImIwMDRkZDJjZDY4ZDRjNDNhZGRlNGVhMzc3MDU5NTI2IiwidXNlcl9pZCI6IjEifQ.pEAr2W7JpTD4O63MyOmqpuX2IbHS5Z8WFpmYhZ_kiis

{
	"name": "Television",
	"price": 300.00,
	"stock": 14,
	"description": "An amazing new TV"
}

###


POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
"username":"konno",
"password":"yuta0126"
}


###


POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
"refresh":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NDIyNDk0NCwiaWF0IjoxNzc0MTM4NTQ0LCJqdGkiOiIwY2E3MzFkOTc3M2E0MTlhOTk0MDIzYmUwMmU5NWY3OCIsInVzZXJfaWQiOiIyIn0.98MmZT_zasWIGAFzq3tmtm_bNRKPCzk_dRZ0IFHGXjw"
}


###

GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MDk3MDk4LCJpYXQiOjE3NzQwOTY3OTgsImp0aSI6IjNmMzI0NGRhNTVlNTRmZGQ5ZWQ4NjUyNWM0ZTkzMTE5IiwidXNlcl9pZCI6IjIifQ.ZU7ZSdjKj4JL_uNjQtt4494U9bczktBmOjtV9QAEJMA
