
GET http://localhost:8000/products/ HTTP/1.1

###

GET http://localhost:8000/products/2/ HTTP/1.1


###

PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

{
	"name": "Television",
	"price": 300.00,
	"stock": 14,
	"description": "An amazing new TV"
}


###

DELETE http://localhost:8000/products/1/ HTTP/1.1


###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer 


{
	"name": "Television",
	"price": 300.00,
	"stock": 14,
	"description": "An amazing new TV"
}

###


POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
"username":"",
"password":""
}


###


POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
"refresh":""
}


###

GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer 

###

GET http://localhost:8000/order/ HTTP/1.1
Authorization: Bearer 

###
GET http://localhost:8000/order/6c857485-d3fd-4f49-b5d6-c913885a8b98 HTTP/1.1
Authorization: Bearer 

###
POST http://10.66.66.4:8000/order/ HTTP/1.1
Content-Type: application/json

{
	"status":"pending",
	"user":1,
	"items":
	[
		{
		"product":2,
		"quantity":2
		},
		{
		"product":3,
		"quantity":1
		}
	]
}
