###

GET http://localhost:3000/user

###

POST http://localhost:3000/user
Content-Type: application/json

{
"name":"",
"email":"faliwceexampleceexle",
"age":40
}

###
GET http://192.168.11.71:3000/user/1

###
DELETE http://localhost:3000/user/15
#
#
###

POST http://192.168.11.71:3000/posts
Content-Type: application/json

{
"userId":1,
"content":"Hello NestJs!",
"title":"My First Post"
}

###

PATCH http://localhost:3000/user/11
Content-Type: application/json

{
"id":11,
"name":"Tom",
"email":"teStfalic@eeXample.com",
"age":40
}


###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"username":"john",
"password":"pass"
}

### 
GET http://localhost:3000/auth/profile


###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
"username":"john",
"password":"pass"
}

### 
GET http://localhost:3000/auth/profile
Authorization: Bearer 


### CATS 
GET http://localhost:3000/cats

### 
GET http://localhost:3000/cats/1

### 
POST http://localhost:3000/cats/

### 
PATCH http://localhost:3000/cats/1

###
DELETE http://localhost:3000/cats/1

