# Generated by Django 6.0.6 on 2026-07-04 23:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                ("short_name", models.CharField(max_length=20, verbose_name="略称")),
                ("rev_exp", models.CharField(max_length=20, verbose_name="費用・売上")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="備考"
                    ),
                ),
                (
                    "slug",
                    models.CharField(max_length=20, unique=True, verbose_name="スラグ"),
                ),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="BMItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bm_work", models.CharField(max_length=50, verbose_name="項目")),
                (
                    "bm_work_sub",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        null=True,
                        verbose_name="補助項目",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="備考")),
                (
                    "slug",
                    models.CharField(max_length=20, unique=True, verbose_name="スラグ"),
                ),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="Broker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="会社名")),
                ("contact", models.CharField(max_length=20, verbose_name="BK担当者名")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="BKEメール"
                    ),
                ),
                (
                    "phone1",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="電話番号"
                    ),
                ),
                (
                    "phone2",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="電話番号2"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="住所"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="短縮名"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Bukken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                ("short_name", models.CharField(max_length=20, verbose_name="略称")),
                (
                    "post_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="郵便番号"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="住所"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="物件タイプ"
                    ),
                ),
                (
                    "build_date",
                    models.DateField(blank=True, null=True, verbose_name="建築日"),
                ),
                (
                    "land_sqm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="土地面積㎡",
                    ),
                ),
                (
                    "build_sqm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="建物面積㎡",
                    ),
                ),
                (
                    "structure",
                    models.CharField(default="", max_length=20, verbose_name="構造"),
                ),
                (
                    "floor_size",
                    models.TextField(
                        blank=True, max_length=50, null=True, verbose_name="規模"
                    ),
                ),
                (
                    "elevator",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="EV"
                    ),
                ),
                (
                    "ceiling",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="天井高"
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="床仕様"
                    ),
                ),
                (
                    "aircon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="空調"
                    ),
                ),
                (
                    "toilet",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="トイレ"
                    ),
                ),
                (
                    "entrance",
                    models.TextField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="エントランス開放時間",
                    ),
                ),
                (
                    "other",
                    models.TextField(
                        blank=True, max_length=150, null=True, verbose_name="その他仕様"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.0,
                        max_digits=10,
                        verbose_name="経度",
                    ),
                ),
                (
                    "longtitude",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.0,
                        max_digits=10,
                        verbose_name="経度",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="備考")),
            ],
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_name", models.CharField(max_length=50, verbose_name="名称")),
                ("short_name", models.CharField(max_length=20, verbose_name="略称")),
                (
                    "post_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="郵便番号"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="住所"
                    ),
                ),
                (
                    "address2",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="住所2"
                    ),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="登録番号"
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="銀行名"
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="支店名"
                    ),
                ),
                (
                    "acount_type",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="預金種別"
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="口座番号"
                    ),
                ),
                (
                    "bank_name_kana",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="口座名義人（カナ）",
                    ),
                ),
                (
                    "bank_name_kanji",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="口座名義人"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guarantor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                ("short_name", models.CharField(max_length=20, verbose_name="略称")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="住所"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="担当者"
                    ),
                ),
                (
                    "email1",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="メール１"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="電話"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="備考"
                    ),
                ),
                (
                    "slug",
                    models.CharField(max_length=20, unique=True, verbose_name="スラグ"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subcontractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                ("short_name", models.CharField(max_length=20, verbose_name="略称")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="住所"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="電話"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="担当者"
                    ),
                ),
                (
                    "email1",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="メール１"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="備考"
                    ),
                ),
                (
                    "slug",
                    models.CharField(max_length=20, unique=True, verbose_name="スラグ"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_rate",
                    models.CharField(
                        default="10%", max_length=20, verbose_name="税率（表示用）"
                    ),
                ),
                (
                    "rate_decimal",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.1,
                        max_digits=5,
                        verbose_name="税率（小数）",
                    ),
                ),
                (
                    "print_form",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="印刷用"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                ("short_name", models.CharField(max_length=20, verbose_name="略称")),
                ("year", models.CharField(max_length=10, verbose_name="入居年")),
                ("floor", models.CharField(max_length=10, verbose_name="基準階")),
                ("base", models.CharField(max_length=10, verbose_name="基準物件")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="住所"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="電話"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="担当者"
                    ),
                ),
                (
                    "email1",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="メール１"
                    ),
                ),
                (
                    "email2",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="メール２"
                    ),
                ),
                (
                    "email3",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="メール３"
                    ),
                ),
                (
                    "email4",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="メール４４"
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="スラグ"
                    ),
                ),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="BMInputField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="レポート日")),
                (
                    "frequency",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="回数"
                    ),
                ),
                (
                    "bm_plan",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="年度予定"
                    ),
                ),
                (
                    "bm_actual",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="実施日"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="備考"
                    ),
                ),
                (
                    "bm_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.bmitem",
                        verbose_name="BM項目",
                    ),
                ),
                (
                    "bukken",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.bukken",
                        verbose_name="物件",
                    ),
                ),
            ],
            options={
                "ordering": ["bm_item__slug"],
            },
        ),
        migrations.CreateModel(
            name="BMFieldSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="回数"
                    ),
                ),
                (
                    "bm_plan",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="年度予定"
                    ),
                ),
                (
                    "bm_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.bmitem",
                        verbose_name="BM項目",
                    ),
                ),
                (
                    "bukken",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.bukken",
                        verbose_name="物件",
                    ),
                ),
            ],
            options={
                "ordering": ["bm_item__slug"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_no",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="部屋番号"
                    ),
                ),
                ("contract_date", models.DateField(verbose_name="契約日")),
                (
                    "original_start_date",
                    models.DateField(verbose_name="当初賃貸開始日"),
                ),
                ("original_end_date", models.DateField(verbose_name="当初賃貸終了日")),
                (
                    "current_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="現在賃貸開始日"
                    ),
                ),
                (
                    "current_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="現在賃貸終了日"
                    ),
                ),
                ("rent_bt", models.IntegerField(default=0, verbose_name="賃料")),
                ("cam", models.IntegerField(default=0, verbose_name="共益費")),
                (
                    "contract_type",
                    models.CharField(
                        default="普通", max_length=50, verbose_name="契約種類"
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(default=True, verbose_name="自動更新"),
                ),
                (
                    "contract_yr",
                    models.IntegerField(default=2, verbose_name="契約年数"),
                ),
                ("renewal", models.BooleanField(default=False, verbose_name="更新料")),
                (
                    "renewal_fee",
                    models.IntegerField(default=0, verbose_name="更新料金額"),
                ),
                (
                    "cancel_notice_time",
                    models.IntegerField(default=6, verbose_name="解約通知"),
                ),
                (
                    "room_type",
                    models.CharField(
                        default="事務所", max_length=20, verbose_name="居室タイプ"
                    ),
                ),
                (
                    "room_sqr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="居室面積㎡",
                    ),
                ),
                (
                    "room_tb",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="居室面積坪",
                    ),
                ),
                (
                    "free_rent",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="フリーレント",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="備考"
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="スラグ"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="退去済"),
                ),
                (
                    "bukken",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.bukken",
                        verbose_name="物件",
                    ),
                ),
                (
                    "guarantor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solitonRE.guarantor",
                        verbose_name="保証会社",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.AddField(
            model_name="bukken",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="solitonRE.entity",
                verbose_name="エンティティ",
            ),
        ),
        migrations.CreateModel(
            name="Revenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="レポート日")),
                ("start_date", models.DateField(verbose_name="該当項目開始日")),
                ("end_date", models.DateField(verbose_name="該当項目終了日")),
                (
                    "invoice_date",
                    models.DateField(blank=True, null=True, verbose_name="請求日"),
                ),
                (
                    "receipt_date",
                    models.DateField(blank=True, null=True, verbose_name="入金日"),
                ),
                ("revenue_bt", models.IntegerField(default=0, verbose_name="売上額")),
                ("revenue_tax", models.IntegerField(default=0, verbose_name="税額")),
                (
                    "revenue_at",
                    models.IntegerField(default=0, verbose_name="税込売上額"),
                ),
                (
                    "invoiceid",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        null=True,
                        verbose_name="請求書ID",
                    ),
                ),
                ("invoice_processed", models.BooleanField(default=False)),
                (
                    "invoice_head_note",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="請求書記載文",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="備考"
                    ),
                ),
                (
                    "account_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.accountcode",
                        verbose_name="収入コード",
                    ),
                ),
                (
                    "bukken",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.bukken",
                        verbose_name="物件",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.contract",
                        verbose_name="契約",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "ordering": ["-contract__room_no", "tenant", "account_code__slug"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoiceid",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="請求書ID",
                    ),
                ),
                (
                    "room_no",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="部屋番号"
                    ),
                ),
                ("report_date", models.DateField(verbose_name="レポート日")),
                (
                    "revenue_bt_ttl_0",
                    models.IntegerField(default=0, verbose_name="無税売上"),
                ),
                ("revenue_bt_ttl", models.IntegerField(default=0, verbose_name="売上")),
                ("tax_ttl", models.IntegerField(default=0, verbose_name="税金")),
                (
                    "revenue_at_ttl",
                    models.IntegerField(default=0, verbose_name="税込売上"),
                ),
                (
                    "revenue_bt_gttl",
                    models.IntegerField(default=0, verbose_name="売上合計"),
                ),
                (
                    "revenue_tax_gttl",
                    models.IntegerField(default=0, verbose_name="合計税額"),
                ),
                (
                    "revenue_at_gttl",
                    models.IntegerField(default=0, verbose_name="税込売上合計"),
                ),
                (
                    "pdf_issued_date",
                    models.DateField(blank=True, null=True, verbose_name="PDF発行日"),
                ),
                (
                    "mail_sent_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="メール送信日"
                    ),
                ),
                (
                    "bukken",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.bukken",
                        verbose_name="物件",
                    ),
                ),
                (
                    "revenue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="solitonRE.revenue",
                        verbose_name="売上",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "ordering": ["-tenant__slug"],
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="レポート日")),
                (
                    "new_tenant",
                    models.TextField(
                        blank=True, null=True, verbose_name="新規テナント"
                    ),
                ),
                (
                    "cur_tenant",
                    models.TextField(
                        blank=True, null=True, verbose_name="テナント状況"
                    ),
                ),
                (
                    "delinquent",
                    models.TextField(blank=True, null=True, verbose_name="遅延状況"),
                ),
                (
                    "inspection",
                    models.TextField(blank=True, null=True, verbose_name="検査"),
                ),
                (
                    "maintenance",
                    models.TextField(
                        blank=True, null=True, verbose_name="メンテナンス"
                    ),
                ),
                (
                    "special_item",
                    models.TextField(blank=True, null=True, verbose_name="特別事項"),
                ),
                (
                    "others",
                    models.TextField(blank=True, null=True, verbose_name="備考"),
                ),
                (
                    "bukken",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.bukken",
                        verbose_name="物件",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseInputField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_bt", models.IntegerField(default=0, verbose_name="支払額")),
                (
                    "account_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.accountcode",
                        verbose_name="収入コード",
                    ),
                ),
                (
                    "bukken",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.bukken",
                        verbose_name="物件",
                    ),
                ),
                (
                    "subcontractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.subcontractor",
                        verbose_name="協力会社",
                    ),
                ),
            ],
            options={
                "ordering": ["account_code__slug"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="レポート日")),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="対象開始時期"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="対象終了時期"
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(blank=True, null=True, verbose_name="請求日"),
                ),
                (
                    "payment_date",
                    models.DateField(blank=True, null=True, verbose_name="支払日"),
                ),
                ("payment_bt", models.IntegerField(default=0, verbose_name="支払額")),
                ("payment_tax", models.IntegerField(default=0, verbose_name="税額")),
                (
                    "payment_at",
                    models.IntegerField(default=0, verbose_name="税込支払額"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="備考"
                    ),
                ),
                (
                    "account_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.accountcode",
                        verbose_name="費用コード",
                    ),
                ),
                (
                    "bukken",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.bukken",
                        verbose_name="物件",
                    ),
                ),
                (
                    "subcontractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.subcontractor",
                        verbose_name="協力会社",
                    ),
                ),
            ],
            options={
                "ordering": ["subcontractor", "account_code__slug"],
            },
        ),
        migrations.AddField(
            model_name="accountcode",
            name="tax_rate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="solitonRE.tax",
                verbose_name="税率",
            ),
        ),
        migrations.CreateModel(
            name="RevInputField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revenue", models.IntegerField(default=0, verbose_name="賃料")),
                (
                    "account_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.accountcode",
                        verbose_name="収入コード",
                    ),
                ),
                (
                    "bukken",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.bukken",
                        verbose_name="物件",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.contract",
                        verbose_name="契約",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant", "contract", "account_code__slug"],
            },
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_months",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="保証金月数"
                    ),
                ),
                (
                    "balance",
                    models.IntegerField(blank=True, null=True, verbose_name="残高"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="備考"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="返済済"),
                ),
                (
                    "bukken",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.bukken",
                        verbose_name="物件",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.contract",
                        verbose_name="契約",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant", "contract__room_no"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceTaxBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revenue_bt", models.IntegerField(default=0, verbose_name="税抜売上")),
                ("tax_amount", models.IntegerField(default=0, verbose_name="税額")),
                ("revenue_at", models.IntegerField(default=0, verbose_name="税込売上")),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_breakdowns",
                        to="solitonRE.invoiceid",
                        verbose_name="請求書",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solitonRE.tax",
                        verbose_name="税率",
                    ),
                ),
            ],
            options={
                "unique_together": {("invoice", "tax_rate")},
            },
        ),
    ]
